### ISSUE TITLE
Odd thing in readme

### ISSUE THREAD

**Issue by malhal** [lorenzofiamingo/SwiftUI-SharedObject#1]
"The problem is that with `@StateObject` the object will deinit with the view"

That is its main advantage so I'm intrigued to know why it's causing a problem for you.

**Comment by lorenzofiamingo** [comment]
The situation I was trying to solve is simply this: using multiple @EnviromentObject of the same class type. Someone could say "just use the @StateObject", but the problem with this is that maybe you would keep alive your object. 
Is not a problem relative to @StateObject but to a specific situation. Thanks for the comment, this points me out I should explain better.

**Comment by malhal** [comment]
If you're using the `environmentObject(object)` modifier you would have had to create a `@StateObject var object = MyObject()` to use anyway.

If the lifecycle is a problem how about moving your `@StateObject` up the View hierarchy?

**Comment by lorenzofiamingo** [comment]
What you would do if you need two different DataFetcher objects in n cell of a list?

**Comment by malhal** [comment]
I would create a single `ObservableObject` to represent the state of the cell, with 2 `@Published `properties for whatever the 2 fetches are getting, e.g. icon and title. I'd call object.fetch() from the cell's `onAppear` which starts both fetches and cancel them both in the object's `deinit`.

**Comment by malhal** [comment]
Actually I probably would break up the cell into sub-Views and use a `@StateObject` in each to fetch each thing separately, I guess it depends if the cell should show anything until both fetches have completed or not. The first way could do that using Combine latest on the fetches.

**Comment by lorenzofiamingo** [comment]
Ok, but I intended a different thing though... anyway I was just trying to imagine a situation where something like @SharableObject can be useful. It is intended when you need to retrieve a shared specific object. Obviously, if every cell needs its own title you'll use `@StateObject` and create a new object. Anyway, `@SharableObject` is a way to do it, not the only one. In my new projects, I put all in a big AppModel like the FrutaApp, because I prefer to follow Apple architectures.

**Comment by malhal** [comment]
At 12mins in the Data essentials in SwiftUI WWDC 2020 talk they say the `ObservableObject` can either be the whole model or just part of it so both approaches are valid. I just had another look at Fruta to check which `View` bodys are recomputed when a property of its big model changes, e.g. if you favourite something then every body that has references the model runs, which would appear inefficient but maybe it's negligible.  Thanks, this discussion has given me a lot to think about.

And btw the image fetching `@StateObject` is shown at 20mins.

**Comment by lorenzofiamingo** [comment]
When a `@Published` property in an object changes, it calls `objectWillChange.send()` that you can call manually too. This publisher (`objectWillChange`) propagates a refresh to all views where the object is referenced (via wrappers).
The best thing to understand is trying yourself. I wrote this when I was trying to understand where the refresh happens.
If you put the `@StateObject` in `AnotherView` the `ContentView` stops being refreshed.
Thanks for the discussion and have a nice day!

    struct ContentView: View {
        
        @StateObject private var obj = Object()
        
        var body: some View {
            VStack {
                Text("This should not change: \(Int.random(in: 0...100))")
                AnotherView(obj: obj).padding(.top)
            }
        }
    }

    struct AnotherView: View {
        
        @ObservedObject var obj: Object
        
        var body: some View {
            // Text("This should change: \(obj.a)")
            Button("Press me") { obj.a = Int.random(in: 0...100) }
        }
    }


    final class Object: ObservableObject {
        @Published var a = 0
    }
