### ISSUE TITLE
Thanks for this wonderful sharedObject

### ISSUE THREAD

**Issue by rnjstjddn96** [lorenzofiamingo/SwiftUI-SharedObject#2]
As I mentioned on title, thank you for sharing this wonderful repo, and I'm currently using it in my code very happly.
However I found that there's a part that printing the typeof ObjectType everytime I interact with it. Could you please remove the 15th line on SharedRepository.swift

**Comment by lorenzofiamingo** [comment]
Thanks for pointing this out! I deleted it and drafted a new release. Cheers!
